# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Artifact(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, stars: float=None, id: str=None):  # noqa: E501
        """Artifact - a model defined in Swagger

        :param stars: The stars of this Artifact.  # noqa: E501
        :type stars: float
        :param id: The id of this Artifact.  # noqa: E501
        :type id: str
        """
        self.swagger_types = {
            'stars': float,
            'id': str
        }

        self.attribute_map = {
            'stars': 'stars',
            'id': 'id'
        }

        self._stars = stars
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'Artifact':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Artifact of this Artifact.  # noqa: E501
        :rtype: Artifact
        """
        return util.deserialize_model(dikt, cls)

    @property
    def stars(self) -> float:
        """Gets the stars of this Artifact.

        Number of stars the artifact is leveled up to  # noqa: E501

        :return: The stars of this Artifact.
        :rtype: float
        """
        return self._stars

    @stars.setter
    def stars(self, stars: float):
        """Sets the stars of this Artifact.

        Number of stars the artifact is leveled up to  # noqa: E501

        :param stars: The stars of this Artifact.
        :type stars: float
        """

        self._stars = stars

    @property
    def id(self) -> str:
        """Gets the id of this Artifact.

        What artifact this refers to  # noqa: E501

        :return: The id of this Artifact.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Artifact.

        What artifact this refers to  # noqa: E501

        :param id: The id of this Artifact.
        :type id: str
        """
        allowed_values = ["queensCrown", "windWalker"]  # noqa: E501
        if id not in allowed_values:
            raise ValueError(
                "Invalid value for `id` ({0}), must be one of {1}"
                .format(id, allowed_values)
            )

        self._id = id
