# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BattlePetRef(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, team: str=None):  # noqa: E501
        """BattlePetRef - a model defined in Swagger

        :param team: The team of this BattlePetRef.  # noqa: E501
        :type team: str
        """
        self.swagger_types = {
            'team': str
        }

        self.attribute_map = {
            'team': 'team'
        }

        self._team = team

    @classmethod
    def from_dict(cls, dikt) -> 'BattlePetRef':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BattlePetRef of this BattlePetRef.  # noqa: E501
        :rtype: BattlePetRef
        """
        return util.deserialize_model(dikt, cls)

    @property
    def team(self) -> str:
        """Gets the team of this BattlePetRef.

        Which side of the battle the referenced hero is on  # noqa: E501

        :return: The team of this BattlePetRef.
        :rtype: str
        """
        return self._team

    @team.setter
    def team(self, team: str):
        """Sets the team of this BattlePetRef.

        Which side of the battle the referenced hero is on  # noqa: E501

        :param team: The team of this BattlePetRef.
        :type team: str
        """
        allowed_values = ["ATTACKING", "DEFENDING"]  # noqa: E501
        if team not in allowed_values:
            raise ValueError(
                "Invalid value for `team` ({0}), must be one of {1}"
                .format(team, allowed_values)
            )

        self._team = team
