# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.round import Round  # noqa: F401,E501
from swagger_server import util


class Battle(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, rounds: List[Round]=None):  # noqa: E501
        """Battle - a model defined in Swagger

        :param rounds: The rounds of this Battle.  # noqa: E501
        :type rounds: List[Round]
        """
        self.swagger_types = {
            'rounds': List[Round]
        }

        self.attribute_map = {
            'rounds': 'rounds'
        }

        self._rounds = rounds

    @classmethod
    def from_dict(cls, dikt) -> 'Battle':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Battle of this Battle.  # noqa: E501
        :rtype: Battle
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rounds(self) -> List[Round]:
        """Gets the rounds of this Battle.


        :return: The rounds of this Battle.
        :rtype: List[Round]
        """
        return self._rounds

    @rounds.setter
    def rounds(self, rounds: List[Round]):
        """Sets the rounds of this Battle.


        :param rounds: The rounds of this Battle.
        :type rounds: List[Round]
        """

        self._rounds = rounds
