# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EquipmentLevel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    GREEN1 = "green1"
    GREEN2 = "green2"
    BLUE1 = "blue1"
    BLUE2 = "blue2"
    YELLOW1 = "yellow1"
    YELLOW2 = "yellow2"
    YELLOW3 = "yellow3"
    PURPLE1 = "purple1"
    PURPLE2 = "purple2"
    PURPLE3 = "purple3"
    PURPLE4 = "purple4"
    ORANGE1 = "orange1"
    ORANGE2 = "orange2"
    ORANGE3 = "orange3"
    ORANGE4 = "orange4"

    def __init__(self):  # noqa: E501
        """EquipmentLevel - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'EquipmentLevel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EquipmentLevel of this EquipmentLevel.  # noqa: E501
        :rtype: EquipmentLevel
        """
        return util.deserialize_model(dikt, cls)
