# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EquipmentLevel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    GREEN1 = "GREEN1"
    GREEN2 = "GREEN2"
    BLUE1 = "BLUE1"
    BLUE2 = "BLUE2"
    YELLOW1 = "YELLOW1"
    YELLOW2 = "YELLOW2"
    YELLOW3 = "YELLOW3"
    PURPLE1 = "PURPLE1"
    PURPLE2 = "PURPLE2"
    PURPLE3 = "PURPLE3"
    PURPLE4 = "PURPLE4"
    ORANGE1 = "ORANGE1"
    ORANGE2 = "ORANGE2"
    ORANGE3 = "ORANGE3"
    ORANGE4 = "ORANGE4"

    def __init__(self):  # noqa: E501
        """EquipmentLevel - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'EquipmentLevel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EquipmentLevel of this EquipmentLevel.  # noqa: E501
        :rtype: EquipmentLevel
        """
        return util.deserialize_model(dikt, cls)
