# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HeroStatsStats(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, hp: float=None, attack: float=None, defense: float=None, speed: float=None, defense_break: float=None, skill_damage: float=None, hit_rate: float=None, dodge: float=None, crit_rate: float=None, crit_damage: float=None, true_damage: float=None, reduce_damage: float=None, control_resist: float=None):  # noqa: E501
        """HeroStatsStats - a model defined in Swagger

        :param hp: The hp of this HeroStatsStats.  # noqa: E501
        :type hp: float
        :param attack: The attack of this HeroStatsStats.  # noqa: E501
        :type attack: float
        :param defense: The defense of this HeroStatsStats.  # noqa: E501
        :type defense: float
        :param speed: The speed of this HeroStatsStats.  # noqa: E501
        :type speed: float
        :param defense_break: The defense_break of this HeroStatsStats.  # noqa: E501
        :type defense_break: float
        :param skill_damage: The skill_damage of this HeroStatsStats.  # noqa: E501
        :type skill_damage: float
        :param hit_rate: The hit_rate of this HeroStatsStats.  # noqa: E501
        :type hit_rate: float
        :param dodge: The dodge of this HeroStatsStats.  # noqa: E501
        :type dodge: float
        :param crit_rate: The crit_rate of this HeroStatsStats.  # noqa: E501
        :type crit_rate: float
        :param crit_damage: The crit_damage of this HeroStatsStats.  # noqa: E501
        :type crit_damage: float
        :param true_damage: The true_damage of this HeroStatsStats.  # noqa: E501
        :type true_damage: float
        :param reduce_damage: The reduce_damage of this HeroStatsStats.  # noqa: E501
        :type reduce_damage: float
        :param control_resist: The control_resist of this HeroStatsStats.  # noqa: E501
        :type control_resist: float
        """
        self.swagger_types = {
            'hp': float,
            'attack': float,
            'defense': float,
            'speed': float,
            'defense_break': float,
            'skill_damage': float,
            'hit_rate': float,
            'dodge': float,
            'crit_rate': float,
            'crit_damage': float,
            'true_damage': float,
            'reduce_damage': float,
            'control_resist': float
        }

        self.attribute_map = {
            'hp': 'hp',
            'attack': 'attack',
            'defense': 'defense',
            'speed': 'speed',
            'defense_break': 'defenseBreak',
            'skill_damage': 'skillDamage',
            'hit_rate': 'hitRate',
            'dodge': 'dodge',
            'crit_rate': 'critRate',
            'crit_damage': 'critDamage',
            'true_damage': 'trueDamage',
            'reduce_damage': 'reduceDamage',
            'control_resist': 'controlResist'
        }

        self._hp = hp
        self._attack = attack
        self._defense = defense
        self._speed = speed
        self._defense_break = defense_break
        self._skill_damage = skill_damage
        self._hit_rate = hit_rate
        self._dodge = dodge
        self._crit_rate = crit_rate
        self._crit_damage = crit_damage
        self._true_damage = true_damage
        self._reduce_damage = reduce_damage
        self._control_resist = control_resist

    @classmethod
    def from_dict(cls, dikt) -> 'HeroStatsStats':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HeroStats_stats of this HeroStatsStats.  # noqa: E501
        :rtype: HeroStatsStats
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hp(self) -> float:
        """Gets the hp of this HeroStatsStats.

        Health of the Hero  # noqa: E501

        :return: The hp of this HeroStatsStats.
        :rtype: float
        """
        return self._hp

    @hp.setter
    def hp(self, hp: float):
        """Sets the hp of this HeroStatsStats.

        Health of the Hero  # noqa: E501

        :param hp: The hp of this HeroStatsStats.
        :type hp: float
        """

        self._hp = hp

    @property
    def attack(self) -> float:
        """Gets the attack of this HeroStatsStats.

        Attack of the Hero  # noqa: E501

        :return: The attack of this HeroStatsStats.
        :rtype: float
        """
        return self._attack

    @attack.setter
    def attack(self, attack: float):
        """Sets the attack of this HeroStatsStats.

        Attack of the Hero  # noqa: E501

        :param attack: The attack of this HeroStatsStats.
        :type attack: float
        """

        self._attack = attack

    @property
    def defense(self) -> float:
        """Gets the defense of this HeroStatsStats.

        Defense of the Hero  # noqa: E501

        :return: The defense of this HeroStatsStats.
        :rtype: float
        """
        return self._defense

    @defense.setter
    def defense(self, defense: float):
        """Sets the defense of this HeroStatsStats.

        Defense of the Hero  # noqa: E501

        :param defense: The defense of this HeroStatsStats.
        :type defense: float
        """

        self._defense = defense

    @property
    def speed(self) -> float:
        """Gets the speed of this HeroStatsStats.

        Speed of the Hero  # noqa: E501

        :return: The speed of this HeroStatsStats.
        :rtype: float
        """
        return self._speed

    @speed.setter
    def speed(self, speed: float):
        """Sets the speed of this HeroStatsStats.

        Speed of the Hero  # noqa: E501

        :param speed: The speed of this HeroStatsStats.
        :type speed: float
        """

        self._speed = speed

    @property
    def defense_break(self) -> float:
        """Gets the defense_break of this HeroStatsStats.

        Defense Break of the Hero  # noqa: E501

        :return: The defense_break of this HeroStatsStats.
        :rtype: float
        """
        return self._defense_break

    @defense_break.setter
    def defense_break(self, defense_break: float):
        """Sets the defense_break of this HeroStatsStats.

        Defense Break of the Hero  # noqa: E501

        :param defense_break: The defense_break of this HeroStatsStats.
        :type defense_break: float
        """

        self._defense_break = defense_break

    @property
    def skill_damage(self) -> float:
        """Gets the skill_damage of this HeroStatsStats.

        Skill Damage of the Hero  # noqa: E501

        :return: The skill_damage of this HeroStatsStats.
        :rtype: float
        """
        return self._skill_damage

    @skill_damage.setter
    def skill_damage(self, skill_damage: float):
        """Sets the skill_damage of this HeroStatsStats.

        Skill Damage of the Hero  # noqa: E501

        :param skill_damage: The skill_damage of this HeroStatsStats.
        :type skill_damage: float
        """

        self._skill_damage = skill_damage

    @property
    def hit_rate(self) -> float:
        """Gets the hit_rate of this HeroStatsStats.

        Hit rate of the Hero (as a bonus which is added to the natural hit rate)  # noqa: E501

        :return: The hit_rate of this HeroStatsStats.
        :rtype: float
        """
        return self._hit_rate

    @hit_rate.setter
    def hit_rate(self, hit_rate: float):
        """Sets the hit_rate of this HeroStatsStats.

        Hit rate of the Hero (as a bonus which is added to the natural hit rate)  # noqa: E501

        :param hit_rate: The hit_rate of this HeroStatsStats.
        :type hit_rate: float
        """

        self._hit_rate = hit_rate

    @property
    def dodge(self) -> float:
        """Gets the dodge of this HeroStatsStats.

        Dodge rate of the Hero  # noqa: E501

        :return: The dodge of this HeroStatsStats.
        :rtype: float
        """
        return self._dodge

    @dodge.setter
    def dodge(self, dodge: float):
        """Sets the dodge of this HeroStatsStats.

        Dodge rate of the Hero  # noqa: E501

        :param dodge: The dodge of this HeroStatsStats.
        :type dodge: float
        """

        self._dodge = dodge

    @property
    def crit_rate(self) -> float:
        """Gets the crit_rate of this HeroStatsStats.

        Crit rate of the Hero  # noqa: E501

        :return: The crit_rate of this HeroStatsStats.
        :rtype: float
        """
        return self._crit_rate

    @crit_rate.setter
    def crit_rate(self, crit_rate: float):
        """Sets the crit_rate of this HeroStatsStats.

        Crit rate of the Hero  # noqa: E501

        :param crit_rate: The crit_rate of this HeroStatsStats.
        :type crit_rate: float
        """

        self._crit_rate = crit_rate

    @property
    def crit_damage(self) -> float:
        """Gets the crit_damage of this HeroStatsStats.

        Crit damage of the Hero (which is added to the natural 50% crit damage bonus)  # noqa: E501

        :return: The crit_damage of this HeroStatsStats.
        :rtype: float
        """
        return self._crit_damage

    @crit_damage.setter
    def crit_damage(self, crit_damage: float):
        """Sets the crit_damage of this HeroStatsStats.

        Crit damage of the Hero (which is added to the natural 50% crit damage bonus)  # noqa: E501

        :param crit_damage: The crit_damage of this HeroStatsStats.
        :type crit_damage: float
        """

        self._crit_damage = crit_damage

    @property
    def true_damage(self) -> float:
        """Gets the true_damage of this HeroStatsStats.

        True damage of the Hero  # noqa: E501

        :return: The true_damage of this HeroStatsStats.
        :rtype: float
        """
        return self._true_damage

    @true_damage.setter
    def true_damage(self, true_damage: float):
        """Sets the true_damage of this HeroStatsStats.

        True damage of the Hero  # noqa: E501

        :param true_damage: The true_damage of this HeroStatsStats.
        :type true_damage: float
        """

        self._true_damage = true_damage

    @property
    def reduce_damage(self) -> float:
        """Gets the reduce_damage of this HeroStatsStats.

        Reduce damage of the Hero  # noqa: E501

        :return: The reduce_damage of this HeroStatsStats.
        :rtype: float
        """
        return self._reduce_damage

    @reduce_damage.setter
    def reduce_damage(self, reduce_damage: float):
        """Sets the reduce_damage of this HeroStatsStats.

        Reduce damage of the Hero  # noqa: E501

        :param reduce_damage: The reduce_damage of this HeroStatsStats.
        :type reduce_damage: float
        """

        self._reduce_damage = reduce_damage

    @property
    def control_resist(self) -> float:
        """Gets the control_resist of this HeroStatsStats.

        Control resist of the Hero  # noqa: E501

        :return: The control_resist of this HeroStatsStats.
        :rtype: float
        """
        return self._control_resist

    @control_resist.setter
    def control_resist(self, control_resist: float):
        """Sets the control_resist of this HeroStatsStats.

        Control resist of the Hero  # noqa: E501

        :param control_resist: The control_resist of this HeroStatsStats.
        :type control_resist: float
        """

        self._control_resist = control_resist
