# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.hero import Hero  # noqa: F401,E501
from swagger_server.models.player import Player  # noqa: F401,E501
from swagger_server import util


class Team(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, player: Player=None, hero_front1: Hero=None, hero_front2: Hero=None, hero_front3: Hero=None, hero_rear1: Hero=None, hero_rear2: Hero=None, hero_rear3: Hero=None):  # noqa: E501
        """Team - a model defined in Swagger

        :param player: The player of this Team.  # noqa: E501
        :type player: Player
        :param hero_front1: The hero_front1 of this Team.  # noqa: E501
        :type hero_front1: Hero
        :param hero_front2: The hero_front2 of this Team.  # noqa: E501
        :type hero_front2: Hero
        :param hero_front3: The hero_front3 of this Team.  # noqa: E501
        :type hero_front3: Hero
        :param hero_rear1: The hero_rear1 of this Team.  # noqa: E501
        :type hero_rear1: Hero
        :param hero_rear2: The hero_rear2 of this Team.  # noqa: E501
        :type hero_rear2: Hero
        :param hero_rear3: The hero_rear3 of this Team.  # noqa: E501
        :type hero_rear3: Hero
        """
        self.swagger_types = {
            'player': Player,
            'hero_front1': Hero,
            'hero_front2': Hero,
            'hero_front3': Hero,
            'hero_rear1': Hero,
            'hero_rear2': Hero,
            'hero_rear3': Hero
        }

        self.attribute_map = {
            'player': 'player',
            'hero_front1': 'heroFront1',
            'hero_front2': 'heroFront2',
            'hero_front3': 'heroFront3',
            'hero_rear1': 'heroRear1',
            'hero_rear2': 'heroRear2',
            'hero_rear3': 'heroRear3'
        }

        self._player = player
        self._hero_front1 = hero_front1
        self._hero_front2 = hero_front2
        self._hero_front3 = hero_front3
        self._hero_rear1 = hero_rear1
        self._hero_rear2 = hero_rear2
        self._hero_rear3 = hero_rear3

    @classmethod
    def from_dict(cls, dikt) -> 'Team':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Team of this Team.  # noqa: E501
        :rtype: Team
        """
        return util.deserialize_model(dikt, cls)

    @property
    def player(self) -> Player:
        """Gets the player of this Team.


        :return: The player of this Team.
        :rtype: Player
        """
        return self._player

    @player.setter
    def player(self, player: Player):
        """Sets the player of this Team.


        :param player: The player of this Team.
        :type player: Player
        """

        self._player = player

    @property
    def hero_front1(self) -> Hero:
        """Gets the hero_front1 of this Team.


        :return: The hero_front1 of this Team.
        :rtype: Hero
        """
        return self._hero_front1

    @hero_front1.setter
    def hero_front1(self, hero_front1: Hero):
        """Sets the hero_front1 of this Team.


        :param hero_front1: The hero_front1 of this Team.
        :type hero_front1: Hero
        """

        self._hero_front1 = hero_front1

    @property
    def hero_front2(self) -> Hero:
        """Gets the hero_front2 of this Team.


        :return: The hero_front2 of this Team.
        :rtype: Hero
        """
        return self._hero_front2

    @hero_front2.setter
    def hero_front2(self, hero_front2: Hero):
        """Sets the hero_front2 of this Team.


        :param hero_front2: The hero_front2 of this Team.
        :type hero_front2: Hero
        """

        self._hero_front2 = hero_front2

    @property
    def hero_front3(self) -> Hero:
        """Gets the hero_front3 of this Team.


        :return: The hero_front3 of this Team.
        :rtype: Hero
        """
        return self._hero_front3

    @hero_front3.setter
    def hero_front3(self, hero_front3: Hero):
        """Sets the hero_front3 of this Team.


        :param hero_front3: The hero_front3 of this Team.
        :type hero_front3: Hero
        """

        self._hero_front3 = hero_front3

    @property
    def hero_rear1(self) -> Hero:
        """Gets the hero_rear1 of this Team.


        :return: The hero_rear1 of this Team.
        :rtype: Hero
        """
        return self._hero_rear1

    @hero_rear1.setter
    def hero_rear1(self, hero_rear1: Hero):
        """Sets the hero_rear1 of this Team.


        :param hero_rear1: The hero_rear1 of this Team.
        :type hero_rear1: Hero
        """

        self._hero_rear1 = hero_rear1

    @property
    def hero_rear2(self) -> Hero:
        """Gets the hero_rear2 of this Team.


        :return: The hero_rear2 of this Team.
        :rtype: Hero
        """
        return self._hero_rear2

    @hero_rear2.setter
    def hero_rear2(self, hero_rear2: Hero):
        """Sets the hero_rear2 of this Team.


        :param hero_rear2: The hero_rear2 of this Team.
        :type hero_rear2: Hero
        """

        self._hero_rear2 = hero_rear2

    @property
    def hero_rear3(self) -> Hero:
        """Gets the hero_rear3 of this Team.


        :return: The hero_rear3 of this Team.
        :rtype: Hero
        """
        return self._hero_rear3

    @hero_rear3.setter
    def hero_rear3(self, hero_rear3: Hero):
        """Sets the hero_rear3 of this Team.


        :param hero_rear3: The hero_rear3 of this Team.
        :type hero_rear3: Hero
        """

        self._hero_rear3 = hero_rear3
